Traceback (most recent call last):
  File "./src/test/python/plot_analytics.py", line 122, in <module>
    a
NameError: name 'a' is not defined
